### PR TITLE
Adds the ability to search.

### LINKED ISSUE #4: Disambiguation is not handled properly.
Search for `Joker`. The output is `Joker may refer to`. Instead of this, a list of possible articles should be shown.

### PR DESCRIPTION
**Pull request by aryadas98**
Adds the ability to search. Fixes #4.
device-2017-12-05-142737
device-2017-12-05-142754

### CODE REVIEW

**Comment by RITESHMOHAPATRA** [comment]
was there any error in content_main.xml and  activity_main.xml????

**Comment by RITESHMOHAPATRA** [comment]
for the current week I am busy , I have not checked it . But was there any
errors in content_main.xml , activity_main.xml ????

**Comment by aryadas98** [comment]
I don't think so. These screenshots are from the final app. I will check.

**Comment by RITESHMOHAPATRA** [comment]
[image: Inline image 1]

there many errors.plz fix it.

**Comment by aryadas98** [comment]
0b4c5bd70648902c1f1c56b76e4a220808496f95 is the source of this issue. Just revert it and everything will work.

**Comment by RITESHMOHAPATRA** [comment]
solved it.

**Pull request merged**
